### PR TITLE
added Payara Tools and updated version to 0.0.3

### PR DESCRIPTION
**Pull request by kathrynkodama**
Added the [Payara Tools VS Code extension](https://marketplace.visualstudio.com/items?itemName=Payara.payara-vscode) to the extension pack 

image

image

Incremented version of the extension pack to `0.0.3`

Fix for #5 
Signed-off-by: Kathryn Kodama <kathryn.s.kodama@gmail.com>

### CODE REVIEW

**Comment by kathrynkodama** [comment]
@rdebusscher can you please review as well

**Comment by yeekangc** [comment]
@rdebusscher, will Payara add a MicroProfile tag to your extension?

**Comment by rdebusscher** [comment]
I guess we can , but it is not MicroProfile only. It is the generic support for Payara within VSCode.

**Comment by yeekangc** [comment]
Yes, we understand that.  The extension is tagged with "Jakarta EE", "Java", and "Payara" today.  Since Payara supports MicroProfile, it will be good to add "MicroProfile" to the list.  Helps with inclusion in the MicroProfile Extension Pack too.

**Comment by rdebusscher** [comment]
I have passed on the request to the appropriate people.

**Comment by rdebusscher** [comment]
Our plugin has now the MicroProfile tag

**Pull request merged**
